# Generated by Django 5.1.1 on 2024-09-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_department_is_manager_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_manager',
        ),
    ]
