# Generated by Django 5.1.1 on 2024-09-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(max_length=10, null='-', unique=True),
            preserve_default='-',
        ),
    ]
